services:
  host:
    build:
      context: ./shell
    ports:
      - "4200:4200"
    volumes:
      - ./shell:/app
      - /app/node_modules   # Exclude node_modules from being replaced
    depends_on:
      - auth
      - tasks
    environment:
      - CHOKIDAR_USEPOLLING=true


  auth:
    build:
      context: ./auth
    ports:
      - "4201:4201"
    volumes:
      - ./auth:/app
      - /app/node_modules   # Exclude node_modules from being replaced
    environment:
      - CHOKIDAR_USEPOLLING=true

  tasks:
    build:
      context: ./tasks
    ports:
      - "4202:4202"
    volumes:
      - ./tasks:/app
      - /app/node_modules   # Exclude node_modules from being replaced
    environment:
      - CHOKIDAR_USEPOLLING=true
